name: release-please
on:
  push:
    branches:
      - main
jobs:
  release_please:
    name: Automated Release
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: manifest
          path: sub-repo1
          monorepo-tags: true
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.releases_created }}
